### ISSUE TITLE
MongoDB docs: Epic 1 v3.10

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#2904]
This epic covers all work for the 3.10 release on Feb 22.

- [x] 1. Replace @default(dbgenerated()) with @default(auto()) for Mongo (PR# 2851)
- [x] 2. No more db.Array (Docs Issue: [#2871](https://github.com/prisma/docs/issues/2871))
- [x] 3. Remove mention of @db.Array from the docs (Docs Issue: [#2816](https://github.com/prisma/docs/issues/2816))
- [x] 4. Doc embedded types: create, createMany, update, updateMany. delete, deleteMany, find, findMany (Docs Issue: [#2796](https://github.com/prisma/docs/issues/2796))
- [x] 5. Update $runCommandRaw example to not use aggregate command (Docs Issue: [#2845](https://github.com/prisma/docs/issues/2845))
- [x] 6. Many-to-many relations will change in 3.10 release.. current docs will not be accurate (refer to [Notion doc](https://www.notion.so/prismaio/MongoDB-Linking-Referencing-Relations-98b51496ac3f48398e1f0571d13ef790)) (Docs Issue: [#2847](https://github.com/prisma/docs/issues/2847))

**Comment by tanberry** [comment]
@keerlu , I created this so that you can have the pleasure of closing it on release day. ;-)
