### ISSUE TITLE
MongoDB docs: Epic 3 for GA v3.12

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#2906]
This epic covers all work for the 3.12 release on April 5th:

## Must Have

- [x] Create new Guide: Using Prisma with MongoDB
- [x] https://github.com/prisma/docs/issues/2767
- [x] https://github.com/prisma/docs/issues/2794
- [x] https://github.com/prisma/docs/issues/2795
- [x] https://github.com/prisma/docs/issues/2986

**Comment by nikolasburk** [comment]
I have created another issue with some suggestions to improve the "Getting Started"-guide: https://github.com/prisma/docs/issues/2916

**Comment by tanberry** [comment]
Done with the GA release in 3.12! @nikolasburk we are moving your issue (https://github.com/prisma/docs/issues/2916) into the next Epic, sorry we didn't get it in for GA.
