### ISSUE TITLE
Epic: MongoDB GA remnants

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3043]
This Issue covers the remaining work that didn't make it into 3.12 release (either code or docs wasn't ready).
- [x] https://github.com/prisma/docs/issues/2916
- [x] https://github.com/prisma/docs/issues/2793
- [x] https://github.com/prisma/docs/issues/2711
- [x] https://github.com/prisma/docs/issues/3007

Lucy edit 30 Jun: removed #2793. This will be tracked as part of full text work instead, see #3350.

**Comment by keerlu** [comment]
Closing the epic as only one issue is still open, which we'll track individually
