### ISSUE TITLE
Epic: Add docs for new PDP functionality

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#3112]
The goal is to document new PDP features for the next release. To clarify later on what all content will include.

- [x] https://github.com/prisma/docs/issues/3252
- [x] https://github.com/prisma/docs/issues/3203
- [x] https://github.com/prisma/docs/issues/3205
- [x] https://github.com/prisma/docs/issues/3253

**Comment by zachtil** [comment]
Closing as all enclosed tasks were completed for PDP GA.
