### ISSUE TITLE
QuickStart Guide: Epic improvements

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3311]
Our QuickStart Guide could use some attention.

- [x] https://github.com/prisma/docs/issues/2812
- [ ] Add a little more info about what exactly happened; the guide is almost too quick
- [ ] Collect feedback from others (@michellegreer @nikolasburk )

**Comment by tanberry** [comment]
Alex R shared this:
Inspiration for the Quickstart/ Getting Started
https://learn.svelte.dev/tutorial/welcome-to-svelte

**Comment by ruheni** [comment]
This is done
