### ISSUE TITLE
Update 'Deploy with AWS Lambda' guide

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#4216]
Update https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-aws-lambda:
- [x] Check steps still work
- [x] Bring language up to style guide standard
- [x] Check whether can cover related issue: #3629 
---
Notes from Andrew:
- Use Zach's [revised Netlify guide](https://docs-git-deploy-netlify-guide-improvemenets-prisma.vercel.app/guides/deployment/deployment-guides/deploying-to-netlify) as a model
