### ISSUE TITLE
`DateTime` documentation improvements

### ISSUE THREAD

**Issue by ruheni** [prisma/prisma2-docs#4732]
```[tasklist]
### Tasks
- [ ] https://github.com/prisma/docs/issues/668
- [ ] https://github.com/prisma/docs/issues/3861
- [ ] https://github.com/prisma/docs/issues/3157
- [ ] https://github.com/prisma/docs/issues/812
- [ ] https://github.com/prisma/docs/issues/548
- [ ] https://github.com/prisma/docs/issues/2755
```

**Comment by jharrell** [comment]
Closing this as we're tracking in the sub issues.
