### ISSUE TITLE
Epic: 4.16.0 (Prisma Client Extensions)

### ISSUE THREAD

**Issue by ruheni** [prisma/prisma2-docs#4842]
```[tasklist]
### Tasks
- [ ] https://github.com/prisma/docs/issues/4865
- [ ] https://github.com/prisma/docs/issues/4866
- [ ] https://github.com/prisma/docs/issues/4867
- [ ] https://github.com/prisma/docs/issues/4868
- [ ] https://github.com/prisma/docs/issues/4871
- [ ] https://github.com/prisma/docs/issues/4840
- [ ] https://github.com/prisma/docs/issues/4870
- [ ] https://github.com/prisma/docs/issues/4880
- [ ] https://github.com/prisma/docs/issues/4883
- [ ] https://github.com/prisma/docs/issues/4869
- [ ] https://github.com/prisma/team-orm/issues/124
- [x] Rename "Prisma Client extensions" to "extensions"
```

**Comment by nikolasburk** [comment]
- [x] Rename "Prisma Client extensions" to "extensions"

**Comment by jharrell** [comment]
This has been retroactively changed to the `4.16.0` epic. `5.0.0` is tracked with #4859
