### ISSUE TITLE
Epic: Deployment guides revamp

### ISSUE THREAD

**Issue by ruheni** [prisma/prisma2-docs#4843]
Execution steps

- [ ] Dependent on https://github.com/prisma/prisma-examples/issues/4792

- [ ] Update the existing serverless & Edge deployment guides
	- [ ] Vercel
	- [ ] Netlify
	- [ ] AWS Lambda (Serverless framework)
	- [ ] AWS Lambda (SST)
	- [ ] Google Cloud functions
	- [ ] Edge™️
		- [ ] Deno Deploy
		- [ ] Vercel Edge functions
		- [ ] Cloudflare workers
- [ ] Add a page that describes different deployment paradigms and how to deploy Prisma
- [ ] Re-evaluate & remove the server-ful guides

**Comment by jharrell** [comment]
Closing this as a duplicate of #4721
