### ISSUE TITLE
Docs Epic: Prisma 5.0.0

### ISSUE THREAD

**Issue by ruheni** [prisma/prisma2-docs#4859]
```[tasklist]
### Tasks
- [ ] https://github.com/prisma/docs/issues/4848
- [ ] https://github.com/prisma/docs/issues/4854
- [ ] https://github.com/prisma/docs/issues/4857
- [ ] https://github.com/prisma/docs/issues/4858
- [ ] https://github.com/prisma/team-orm/issues/207
- [ ] https://github.com/prisma/docs/issues/5006
- [ ] https://github.com/prisma/docs/issues/5000
- [ ] https://github.com/prisma/docs/issues/4999
- [ ] https://github.com/prisma/docs/issues/4998
- [ ] https://github.com/prisma/docs/pull/4789
- [ ] https://github.com/prisma/docs/pull/4928
- [ ] https://github.com/prisma/docs/pull/5015
```
```[tasklist]
### These are not part of Prisma 5 anymore, no commucation needed
- [x] Removal of deprecated `PRISMA_BINARIES_MIRROR` env var
- [ ] https://github.com/prisma/docs/issues/4856
```
