### ISSUE TITLE
Epic: Prisma 5 Upgrade Guide Upgrades

### ISSUE THREAD

**Issue by jharrell** [prisma/prisma2-docs#5043]
```[tasklist]
- [ ] https://github.com/prisma/docs/issues/5016
- [ ] https://github.com/prisma/docs/issues/5025
- [ ] https://github.com/prisma/docs/issues/5044
- [ ] https://github.com/prisma/docs/issues/5046
- [ ] https://github.com/prisma/docs/issues/5066
```
